// <auto-generated />
using System;
using GridProjectPortals.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GridProjectPortals.DB.Migrations
{
    [DbContext(typeof(GridDbContext))]
    [Migration("20240321123553_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GridProjectPortals.Domain.Tables.tblEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblEmployees");
                });

            modelBuilder.Entity("GridProjectPortals.Domain.Tables.tblGridColumnDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GridName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblGridColumnDef");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GridName = "grdEmployeeDetails",
                            PageId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("GridProjectPortals.Domain.Tables.tblGridColumnDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnDataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GridId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<bool?>("isFix")
                        .HasColumnType("bit");

                    b.Property<bool?>("isSearchable")
                        .HasColumnType("bit");

                    b.Property<bool?>("isVisible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblGridColumnDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColumnDataType = "int",
                            ColumnName = "id",
                            GridId = 1,
                            Sequence = 1,
                            isFix = false,
                            isSearchable = false,
                            isVisible = false
                        },
                        new
                        {
                            Id = 2,
                            ColumnDataType = "string",
                            ColumnName = "FirstName",
                            GridId = 1,
                            Sequence = 2,
                            isFix = false,
                            isSearchable = true,
                            isVisible = true
                        },
                        new
                        {
                            Id = 3,
                            ColumnDataType = "string",
                            ColumnName = "lastName",
                            GridId = 1,
                            Sequence = 3,
                            isFix = false,
                            isSearchable = true,
                            isVisible = true
                        },
                        new
                        {
                            Id = 4,
                            ColumnDataType = "string",
                            ColumnName = "UserName",
                            GridId = 1,
                            Sequence = 4,
                            isFix = false,
                            isSearchable = true,
                            isVisible = true
                        },
                        new
                        {
                            Id = 5,
                            ColumnDataType = "string",
                            ColumnName = "Phone",
                            GridId = 1,
                            Sequence = 5,
                            isFix = false,
                            isSearchable = true,
                            isVisible = true
                        });
                });

            modelBuilder.Entity("GridProjectPortals.Domain.Tables.tblGridPages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Page")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblGridPages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Page = "Employees"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
